// V3 시나리오 90개 (a: Top 3 fine-tuning 30 + b: 안 시도 8방향 60)
//
// Part A (Loops 91-120): V2 Top 3 (#58·#90·#88) fine-tuning + 영진·정환·두흥 강화
// Part B (Loops 121-180): 격국 base 차등, 사주 강약 페널티 약화, 충형해파 시기별,
//                          신살 카운트 multiplier, 상관·정재격 별도 시그너,
//                          두흥 외부변수, V3 통합 후보

export interface CalibConfig {
  id: number;
  name: string;
  hypothesis: string;
  baseScore: number;
  weights: Record<string, number>;
}

export const V7_BASE = {
  g_jeongin: 12, g_pyeonin: 12, g_jeonggwan: 12, g_siksin: 12, g_bigyeon: 12,
  s_gwaninCombo: 15, s_insung2: 8, s_insung3: 12,
  gw_hakdang: 4, gw_munchang: 4, gw_mungok: 2, gw_cheoneul: 4, gw_twoVirtues: 5, gw_samgwi: 5, gw_samgi: 5,
  u_dayGeonrok: 5, u_dayTonggeun: 5,
  d_youthInsung: 8, d_youthGwansung: 5,
};

// V2 Top 3 weights (V3 starting points)
const V2_58 = { ...V7_BASE, g_jeongin: 25, g_pyeonin: 22, g_jeongjae: 8, g_yangin: 15, g_sanggwan: 8, s_gwaninCombo: 22, combo_jarip: 20, combo_yanginScholar: 15, combo_youngshik: 10, gw_samgwi: 8, gw_twoVirtues: 8, d_youthInsung: 12, d_youthGwansung: 8 };
const V2_90 = { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_jeonggwan: 22, g_pyeongwan: 15, g_siksin: 18, g_bigyeon: 15, g_yangin: 12, g_jeongjae: 8, g_pyeonjae: 8, g_sanggwan: 8, combo_allScholar: 25, combo_jarip: 20, combo_yanginScholar: 18, combo_youngshik: 12, s_gwaninCombo: 18, cnt_insung: 4, cnt_gui_total: 4, cnt_jaesung: -3, d_youthInsung: 15, d_youthJaesung: -8 };
const V2_88 = { ...V7_BASE, g_jeongin: 25, g_pyeonin: 22, g_jeonggwan: 22, g_siksin: 18, g_bigyeon: 15, g_yangin: 12, g_pyeongwan: 15, g_jeongjae: 10, g_sanggwan: 10, g_pyeonjae: 8, combo_allScholar: 25, combo_jarip: 18, cnt_insung: 4, cnt_gui_total: 4, s_gwaninCombo: 18 };

// 평균 helper
function avg(...sets: Array<Record<string, number>>): Record<string, number> {
  const keys = new Set<string>();
  for (const s of sets) Object.keys(s).forEach(k => keys.add(k));
  const out: Record<string, number> = {};
  for (const k of keys) {
    const vals = sets.map(s => s[k] ?? 0);
    out[k] = Math.round(vals.reduce((a, b) => a + b, 0) / sets.length);
  }
  return out;
}
const V2_58_90_AVG = avg(V2_58, V2_90);
const V2_TOP3_AVG = avg(V2_58, V2_90, V2_88);

export const SCENARIOS: CalibConfig[] = [
  // ============ Part A: V2 Top 3 fine-tuning + sample별 강화 (91-120, 30개) ============

  // A1. #58 fine-tuning (91-95)
  { id: 91, name: '#58 + 영진 강화 (g_sanggwan: 14, cnt_siksang +2)',
    hypothesis: 'V2 #58 base 18 + 상관격 base ↑로 영진 4-2 도달 시도',
    baseScore: 18,
    weights: { ...V2_58, g_sanggwan: 14, cnt_siksang: 2 },
  },
  { id: 92, name: '#58 + 정환 강화 (g_jeongjae: 14, d_youthGwansung ×1.5)',
    hypothesis: '정재격 강화 + 청소년 관성 가중',
    baseScore: 18,
    weights: { ...V2_58, g_jeongjae: 14, d_youthGwansung: 14, s_gwaninCombo: 26 },
  },
  { id: 93, name: '#58 + 영진 + 정환 결합',
    hypothesis: 'A91·A92 결합',
    baseScore: 18,
    weights: { ...V2_58, g_sanggwan: 14, g_jeongjae: 14, d_youthGwansung: 14, cnt_siksang: 2 },
  },
  { id: 94, name: '#58 + cnt_jaesung -3 + cnt_insung +3',
    hypothesis: '재성 페널티 + 인성 multiplier 추가',
    baseScore: 18,
    weights: { ...V2_58, cnt_jaesung: -3, cnt_insung: 3 },
  },
  { id: 95, name: '#58 + 비학자 격국 base 평준화',
    hypothesis: '비학자 격국 8 → 12 평준화 (영진·정환·와이프 동시)',
    baseScore: 18,
    weights: { ...V2_58, g_sanggwan: 12, g_jeongjae: 12, g_pyeonjae: 12, g_pyeongwan: 12 },
  },

  // A2. #90 fine-tuning (96-100)
  { id: 96, name: '#90 + 영진 강화 (g_sanggwan: 14, cnt_siksang +3)',
    hypothesis: 'V2 #90 + 상관격 강화',
    baseScore: 18,
    weights: { ...V2_90, g_sanggwan: 14, cnt_siksang: 3 },
  },
  { id: 97, name: '#90 + 정환 강화 (d_youthGwansung +12)',
    hypothesis: '정환 청소년 관성 강',
    baseScore: 18,
    weights: { ...V2_90, g_jeongjae: 14, d_youthGwansung: 17 },
  },
  { id: 98, name: '#90 + 영진 + 정환 결합',
    hypothesis: 'A96·A97 결합',
    baseScore: 18,
    weights: { ...V2_90, g_sanggwan: 14, g_jeongjae: 14, cnt_siksang: 3, d_youthGwansung: 17 },
  },
  { id: 99, name: '#90 weights ×0.85 (인플레 감쇠)',
    hypothesis: 'V2 #90 mean 너무 높음 — weight 감쇠로 분포 spread 확보',
    baseScore: 12,
    weights: Object.fromEntries(Object.entries(V2_90).map(([k, v]) => [k, Math.round(v * 0.85)])),
  },
  { id: 100, name: '#90 + sample별 종합 미세',
    hypothesis: '#90 + 영진·정환·와이프·승희 동시 미세',
    baseScore: 18,
    weights: { ...V2_90, g_sanggwan: 12, g_jeongjae: 13, d_youthGwansung: 12, gw_samgwi: 10 },
  },

  // A3. #58 + #90 hybrid (101-105)
  { id: 101, name: '(#58 + #90) / 2 평균',
    hypothesis: '두 최강 weight 평균',
    baseScore: 18,
    weights: V2_58_90_AVG,
  },
  { id: 102, name: '평균 + 영진 강화',
    hypothesis: 'V2_58_90_AVG + g_sanggwan: 14, cnt_siksang +2',
    baseScore: 18,
    weights: { ...V2_58_90_AVG, g_sanggwan: 14, cnt_siksang: 2 },
  },
  { id: 103, name: '평균 + 정환 강화',
    hypothesis: 'V2_58_90_AVG + g_jeongjae: 14, d_youthGwansung +12',
    baseScore: 18,
    weights: { ...V2_58_90_AVG, g_jeongjae: 14, d_youthGwansung: 16 },
  },
  { id: 104, name: '평균 + 영진 + 정환',
    hypothesis: 'V2_58_90_AVG + A102·A103',
    baseScore: 18,
    weights: { ...V2_58_90_AVG, g_sanggwan: 14, g_jeongjae: 14, d_youthGwansung: 16, cnt_siksang: 2 },
  },
  { id: 105, name: '평균 + cnt 강화 (insung·gui ×5)',
    hypothesis: 'V2_58_90_AVG + cnt multiplier 강화',
    baseScore: 18,
    weights: { ...V2_58_90_AVG, cnt_insung: 5, cnt_gui_total: 5, cnt_cheoneul: 3 },
  },

  // A4. 영진 (상관격 4-2) 강화 (106-110)
  { id: 106, name: '상관격 base 학자형의 70%',
    hypothesis: 'g_sanggwan: 18 (학자형 25 대비 70%)',
    baseScore: 18,
    weights: { ...V7_BASE, g_jeongin: 25, g_pyeonin: 22, g_jeonggwan: 22, g_sanggwan: 18, g_siksin: 20, s_gwaninCombo: 22 },
  },
  { id: 107, name: '청소년 식상 대운 +10 (영진 패턴)',
    hypothesis: 'd_youthSiksang: 10 신규',
    baseScore: 15,
    weights: { ...V2_58, g_sanggwan: 15, d_youthSiksang: 10 },
  },
  { id: 108, name: '상관격 + 천을 multiplier ×4',
    hypothesis: '비학자 격국이라도 천을 카운트로 보강',
    baseScore: 15,
    weights: { ...V2_58, g_sanggwan: 14, cnt_cheoneul: 4 },
  },
  { id: 109, name: '상관격 + 천을·학당 강',
    hypothesis: '비학자 격국 + 신살 카운트 종합',
    baseScore: 15,
    weights: { ...V2_58, g_sanggwan: 14, cnt_cheoneul: 5, cnt_hakdang: 4, cnt_munchang: 3 },
  },
  { id: 110, name: '상관격 + 일주 통근 +12',
    hypothesis: '상관격이지만 일주 강하면 능력 보강',
    baseScore: 15,
    weights: { ...V2_58, g_sanggwan: 14, u_dayGeonrok: 12, u_dayTonggeun: 12, u_monthStrong: 8 },
  },

  // A5. 정환 (정재격 1-2) 강화 (111-115)
  { id: 111, name: '정재격 base 학자형의 80%',
    hypothesis: 'g_jeongjae: 20',
    baseScore: 18,
    weights: { ...V7_BASE, g_jeongin: 25, g_pyeonin: 22, g_jeonggwan: 22, g_jeongjae: 20, g_siksin: 20, s_gwaninCombo: 22 },
  },
  { id: 112, name: '정재격 + 관인상생 ×1.5',
    hypothesis: 's_gwaninCombo: 30 강화',
    baseScore: 15,
    weights: { ...V2_58, g_jeongjae: 14, s_gwaninCombo: 30, s_insung3: 18 },
  },
  { id: 113, name: '정재격 + 청소년 관성 +18',
    hypothesis: 'd_youthGwansung: 18',
    baseScore: 15,
    weights: { ...V2_58, g_jeongjae: 14, d_youthGwansung: 18, d_youthInsung: 15 },
  },
  { id: 114, name: '정재격 + 학자귀인 ≥ 2 콤보 +15',
    hypothesis: 'cnt_gui_total × 5 + 학자귀인 ≥ 2 강화',
    baseScore: 15,
    weights: { ...V2_58, g_jeongjae: 14, cnt_gui_total: 5, s_gui_2plus: 12 },
  },
  { id: 115, name: '정재격 + cnt_gwansung × 4',
    hypothesis: '관성 multiplier로 정재 보강',
    baseScore: 15,
    weights: { ...V2_58, g_jeongjae: 14, cnt_gwansung: 4, s_gwaninCombo: 25 },
  },

  // A6. 두흥 외부변수 — 사주 본질 강 패턴 (116-120)
  { id: 116, name: '#90 + cnt_bigeop × 3 (두흥 비겁왕 사주)',
    hypothesis: '비견·겁재 multiplier로 본질 강 sample 잡기',
    baseScore: 18,
    weights: { ...V2_90, cnt_bigeop: 3 },
  },
  { id: 117, name: '#90 + 양인격 + 비견격 base ↑',
    hypothesis: 'g_yangin: 18, g_bigyeon: 18',
    baseScore: 18,
    weights: { ...V2_90, g_yangin: 18, g_bigyeon: 18 },
  },
  { id: 118, name: '#90 + 인성왕 (cnt_insung × 6) + 비견왕',
    hypothesis: '인성·비겁 multiplier 동시',
    baseScore: 18,
    weights: { ...V2_90, cnt_insung: 6, cnt_bigeop: 3 },
  },
  { id: 119, name: '#90 + 양인 학자 + 통근 강',
    hypothesis: 'combo_yanginScholar + u_dayGeonrok 동시 강',
    baseScore: 18,
    weights: { ...V2_90, combo_yanginScholar: 22, u_dayGeonrok: 12, u_dayTonggeun: 12 },
  },
  { id: 120, name: '#58 + 모든 sample 미세 종합',
    hypothesis: 'A102 + A116 + A111',
    baseScore: 18,
    weights: { ...V2_58_90_AVG, g_sanggwan: 14, g_jeongjae: 14, cnt_bigeop: 3, d_youthGwansung: 16 },
  },

  // ============ Part B: 안 시도 8방향 (121-180, 60개) ============

  // B1. 격국별 base 차등 (121-130)
  { id: 121, name: '학자형 base 30, 비학자 base 10',
    hypothesis: '격국 자체로 본질 분리',
    baseScore: 10,
    weights: { ...V7_BASE, g_jeongin: 30, g_pyeonin: 28, g_jeonggwan: 28, g_siksin: 25, g_bigyeon: 18, g_yangin: 15, g_pyeongwan: 22, g_jeongjae: 10, g_pyeonjae: 8, g_sanggwan: 10 },
  },
  { id: 122, name: '학자형 25, 양인 22, 비학자 12',
    hypothesis: '3단계 격국 grade',
    baseScore: 12,
    weights: { ...V7_BASE, g_jeongin: 25, g_pyeonin: 25, g_jeonggwan: 25, g_siksin: 22, g_pyeongwan: 22, g_yangin: 22, g_bigyeon: 18, g_jeongjae: 12, g_pyeonjae: 12, g_sanggwan: 12 },
  },
  { id: 123, name: '학자형 28, 비견·양인 18, 상관·정재 15',
    hypothesis: '학자형 일관 강 + 비학자 평준화',
    baseScore: 12,
    weights: { ...V7_BASE, g_jeongin: 28, g_pyeonin: 28, g_jeonggwan: 28, g_siksin: 25, g_pyeongwan: 22, g_bigyeon: 18, g_yangin: 18, g_jeongjae: 15, g_pyeonjae: 12, g_sanggwan: 15 },
  },
  { id: 124, name: 'base 25 + 격국 weight 0 (격국 외 요소만)',
    hypothesis: '격국 의존도 제로 — 십성·신살·운성만',
    baseScore: 25,
    weights: { s_gwaninCombo: 25, s_insung3: 18, s_insung2: 10, combo_allScholar: 25, combo_jarip: 18, gw_hakdang: 6, gw_munchang: 6, gw_cheoneul: 6, gw_twoVirtues: 6, u_dayGeonrok: 8, u_dayTonggeun: 8, d_youthInsung: 12 },
  },
  { id: 125, name: '학자형 base 25 + 격국 weight 15 (이중)',
    hypothesis: '학자형 격국에 base + weight 둘 다',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_jeonggwan: 22, g_siksin: 18, g_pyeongwan: 18, g_bigyeon: 12, g_yangin: 10, g_jeongjae: 8, g_pyeonjae: 8, g_sanggwan: 8, s_gwaninCombo: 20, combo_allScholar: 22 },
  },
  { id: 126, name: '격국별 base (양인 22, 식신 25, 정인 30, 편인 28, 정관 28)',
    hypothesis: '격국별 강도 차등 + 12운성',
    baseScore: 10,
    weights: { g_jeongin: 30, g_pyeonin: 28, g_jeonggwan: 28, g_pyeongwan: 22, g_siksin: 25, g_bigyeon: 18, g_yangin: 22, g_jeongjae: 12, g_pyeonjae: 10, g_sanggwan: 12, s_gwaninCombo: 18, u_dayGeonrok: 8, u_dayTonggeun: 8 },
  },
  { id: 127, name: '격국 + 인성≥3 동시 = base 35',
    hypothesis: '학자형 격국 AND 인성왕 = 최강',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_jeonggwan: 22, s_insung3: 20, s_gwaninCombo: 25, combo_allScholar: 25 },
  },
  { id: 128, name: '격국 + 일주 통근 동시 = base 25',
    hypothesis: '격국 학자 AND 일주 강 = 양호',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_jeonggwan: 22, u_dayGeonrok: 12, u_dayTonggeun: 12, u_monthStrong: 10, s_gwaninCombo: 20 },
  },
  { id: 129, name: '격국 그라데이션 ×1.5 (정인 45, 편인 38, …)',
    hypothesis: 'V1 #5 정인 30 → 45 강화',
    baseScore: 8,
    weights: { ...V7_BASE, g_jeongin: 45, g_pyeonin: 38, g_jeonggwan: 38, g_siksin: 30, g_pyeongwan: 28, g_bigyeon: 22, g_yangin: 18, g_jeongjae: 15, g_pyeonjae: 12, g_sanggwan: 12 },
  },
  { id: 130, name: '격국 base + cnt multiplier 동시',
    hypothesis: '격국 차등 + 십성 카운트 multiplier 종합',
    baseScore: 12,
    weights: { g_jeongin: 25, g_pyeonin: 22, g_jeonggwan: 22, g_siksin: 20, g_pyeongwan: 18, g_bigyeon: 15, g_yangin: 15, g_jeongjae: 10, g_pyeonjae: 10, g_sanggwan: 10, cnt_insung: 4, cnt_gwansung: 3, cnt_gui_total: 4, s_gwaninCombo: 18 },
  },

  // B2. 사주 강약 페널티 약화 (131-135)
  { id: 131, name: '모든 음수 weight 제거 (페널티 baseline)',
    hypothesis: 'V2 페널티 시도와 비교 — 페널티 0',
    baseScore: 18,
    weights: { ...V2_90, cnt_jaesung: 0, d_youthJaesung: 0 },
  },
  { id: 132, name: '인성 ≥ 3 = combo +15 (페널티 대신 보너스)',
    hypothesis: '강한 사주는 페널티 제거 + 보너스',
    baseScore: 18,
    weights: { ...V2_90, s_insung3: 27, cnt_jaesung: 0, d_youthJaesung: 0 },
  },
  { id: 133, name: '격국 학자형 + 인성왕 = +20 콤보',
    hypothesis: '강한 사주 자동 보너스',
    baseScore: 18,
    weights: { ...V2_90, combo_allScholar: 35, cnt_jaesung: 0, d_youthJaesung: 0 },
  },
  { id: 134, name: '사주 강 = +25 (gwaninsangsaeng + 인성≥3)',
    hypothesis: '관인상생 + 인성왕 동시 = 강 마크',
    baseScore: 18,
    weights: { ...V2_90, combo_gwaninStrong: 25, s_insung3: 18, cnt_jaesung: 0 },
  },
  { id: 135, name: '사주 3티어 분리 (강·중·약)',
    hypothesis: '인성≥3=강(+15), 인성2=중(+5), 인성0-1=약(-5)',
    baseScore: 18,
    weights: { ...V2_90, s_insung3: 20, s_insung2: 12, s_insung_1plus: -3 },
  },

  // B3. 충형해파 시기·강도별 (136-140)
  { id: 136, name: '청소년 충형 -8 + 입시 충 -15',
    hypothesis: '시기별 강도 차등',
    baseScore: 22,
    weights: { ...V2_58, d_youthChungHyeong: -8 },
  },
  { id: 137, name: '충형해파 + cnt multiplier',
    hypothesis: '충형 보유 × -3',
    baseScore: 20,
    weights: { ...V2_58, d_youthChungHyeong: -10, sh_gongmang: -5 },
  },
  { id: 138, name: '청소년 충 -8 / 일지 약 -8 / 식상 -5',
    hypothesis: '여러 부정 시그너 동시',
    baseScore: 22,
    weights: { ...V2_58, d_youthChungHyeong: -8, u_dayWeak: -8, d_youthSiksang: -5 },
  },
  { id: 139, name: '충형해파 -2 × cnt',
    hypothesis: '카운트 페널티',
    baseScore: 20,
    weights: { ...V2_58, d_youthChungHyeong: -6, sh_gongmang: -4 },
  },
  { id: 140, name: '청소년 충 + 일지 약 콤보 -15',
    hypothesis: '두 시그너 동시 발동 시 강 페널티',
    baseScore: 22,
    weights: { ...V2_58, d_youthChungHyeong: -10, u_dayWeak: -5 },
  },

  // B4. 신살 카운트 multiplier (141-145)
  { id: 141, name: '천을 ×4 + 학당 ×4 + 문창 ×3',
    hypothesis: '신살 multiplier 강화',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, s_gwaninCombo: 22, cnt_cheoneul: 4, cnt_hakdang: 4, cnt_munchang: 3 },
  },
  { id: 142, name: '학자귀인 cnt × 5',
    hypothesis: '학당+문창+문곡 합산 multiplier',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, s_gwaninCombo: 22, cnt_gui_total: 5 },
  },
  { id: 143, name: '모든 신살 cnt × 3 종합',
    hypothesis: '신살 종합 multiplier',
    baseScore: 12,
    weights: { ...V7_BASE, g_jeongin: 20, g_pyeonin: 20, s_gwaninCombo: 20, cnt_cheoneul: 3, cnt_hakdang: 3, cnt_munchang: 3, cnt_mungok: 3 },
  },
  { id: 144, name: '천을 ×5 + 학자귀인 ×5 + 학자형 base 25',
    hypothesis: '신살 강 + 격국 base',
    baseScore: 15,
    weights: { g_jeongin: 25, g_pyeonin: 25, g_jeonggwan: 25, g_siksin: 22, g_bigyeon: 15, g_yangin: 15, g_jeongjae: 10, g_pyeonjae: 10, g_sanggwan: 10, g_pyeongwan: 18, s_gwaninCombo: 20, cnt_cheoneul: 5, cnt_gui_total: 5 },
  },
  { id: 145, name: '신살 cnt + cnt_insung × 5',
    hypothesis: '신살 + 십성 카운트 동시',
    baseScore: 12,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, s_gwaninCombo: 22, cnt_cheoneul: 4, cnt_gui_total: 4, cnt_insung: 5 },
  },

  // B5. 상관격·정재격 별도 시그너 (146-155)
  { id: 146, name: '상관격 base 15 + 식상 multiplier × 3',
    hypothesis: '상관격 본질 시그너',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_jeonggwan: 22, g_sanggwan: 15, cnt_siksang: 3, s_gwaninCombo: 22 },
  },
  { id: 147, name: '정재격 base 15 + 관인상생 강',
    hypothesis: '정재격 본질 시그너',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_jeonggwan: 22, g_jeongjae: 15, s_gwaninCombo: 28, s_insung3: 18 },
  },
  { id: 148, name: '상관·정재격 base 학자형 70%',
    hypothesis: 'g_sanggwan: 18 + g_jeongjae: 18',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 25, g_pyeonin: 22, g_jeonggwan: 22, g_sanggwan: 18, g_jeongjae: 18, s_gwaninCombo: 22 },
  },
  { id: 149, name: '상관격 + 인성 ≥ 2 콤보 +20',
    hypothesis: '상관격 + 인성 양호 = 능력 보강',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_sanggwan: 14, s_insung2: 15, s_insung3: 20, s_gwaninCombo: 22 },
  },
  { id: 150, name: '정재격 + 인성 ≥ 2 콤보 +20 (재성 인성 갈등 보완)',
    hypothesis: '정재격 + 인성 양호 = 학자형 가능',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_jeongjae: 14, s_insung2: 15, s_insung3: 20, s_gwaninCombo: 25 },
  },
  { id: 151, name: '상관·정재격 + 청소년 관성 대운 +18',
    hypothesis: '비학자 격국이라도 청소년 관성 강하면 학업↑',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_sanggwan: 14, g_jeongjae: 14, d_youthGwansung: 18, s_gwaninCombo: 22 },
  },
  { id: 152, name: '상관격 별도 시그너 (g_sanggwan: 18 + cnt_siksang × 3)',
    hypothesis: '상관격 본질 multiplier',
    baseScore: 12,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_sanggwan: 18, cnt_siksang: 3, s_gwaninCombo: 22 },
  },
  { id: 153, name: '정재격 별도 시그너 (g_jeongjae: 18 + cnt_jaesung -2)',
    hypothesis: '정재격 base ↑ 단 재성왕 (≥3)은 페널티',
    baseScore: 12,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_jeongjae: 18, cnt_jaesung: -2, s_gwaninCombo: 22 },
  },
  { id: 154, name: '상관·정재격 base 동등 (둘 다 15)',
    hypothesis: '두 격국 동시 base 15 (학자형 평균)',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_sanggwan: 15, g_jeongjae: 15, s_gwaninCombo: 22 },
  },
  { id: 155, name: '상관·정재격 + 학자귀인 ≥ 2 콤보 +15',
    hypothesis: '비학자 격국 + 학자귀인 다중 = 학자형 인정',
    baseScore: 12,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_sanggwan: 14, g_jeongjae: 14, cnt_gui_total: 5, s_gui_2plus: 15, s_gwaninCombo: 22 },
  },

  // B6. 두흥 외부변수 명시 — 사주 본질 강 시그너 (156-160)
  { id: 156, name: '비겁 multiplier (cnt_bigeop × 4)',
    hypothesis: '비겁왕 사주 본질 강',
    baseScore: 15,
    weights: { ...V2_58, cnt_bigeop: 4 },
  },
  { id: 157, name: 'cnt_insung × 5 + cnt_bigeop × 3',
    hypothesis: '인성·비겁 multiplier 동시',
    baseScore: 12,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, cnt_insung: 5, cnt_bigeop: 3, s_gwaninCombo: 22 },
  },
  { id: 158, name: '양인 + 비견격 base ↑ (g_yangin: 22, g_bigyeon: 20)',
    hypothesis: '두흥류 본질 강 격국',
    baseScore: 15,
    weights: { ...V2_58, g_yangin: 22, g_bigyeon: 20 },
  },
  { id: 159, name: '양인격 +20 multiplier',
    hypothesis: '양인격 자체 학자형 인정',
    baseScore: 15,
    weights: { ...V2_58, g_yangin: 25, combo_yanginScholar: 25 },
  },
  { id: 160, name: '비견격 +15 + 일지 건록',
    hypothesis: '비견격 + 일주 강',
    baseScore: 15,
    weights: { ...V2_58, g_bigyeon: 22, u_dayGeonrok: 15 },
  },

  // B7. V3 통합 후보 (161-180)
  { id: 161, name: 'A106 + B1.122 + B5.146 (상관격 종합)',
    hypothesis: '영진 강화 통합 1',
    baseScore: 15,
    weights: { g_jeongin: 25, g_pyeonin: 25, g_jeonggwan: 25, g_siksin: 22, g_pyeongwan: 22, g_yangin: 22, g_bigyeon: 18, g_sanggwan: 18, g_jeongjae: 12, g_pyeonjae: 12, s_gwaninCombo: 22, cnt_siksang: 3 },
  },
  { id: 162, name: 'A112 + B1.123 + B5.150 (정환 강화 통합)',
    hypothesis: '정환 강화 통합 1',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 28, g_pyeonin: 28, g_jeonggwan: 28, g_siksin: 25, g_pyeongwan: 22, g_bigyeon: 18, g_yangin: 18, g_jeongjae: 18, g_sanggwan: 15, s_gwaninCombo: 28, s_insung3: 20 },
  },
  { id: 163, name: '평균 + B2.132 (강 사주 보너스)',
    hypothesis: '#58·#90 평균 + 인성왕 보너스',
    baseScore: 18,
    weights: { ...V2_58_90_AVG, s_insung3: 27, cnt_jaesung: 0 },
  },
  { id: 164, name: '#58 + B4.141 + B5.147',
    hypothesis: '신살 multi + 정재격 본질',
    baseScore: 15,
    weights: { ...V2_58, g_jeongjae: 14, cnt_cheoneul: 4, cnt_hakdang: 4, cnt_munchang: 3 },
  },
  { id: 165, name: '#90 + B4.144 + B6.157',
    hypothesis: '신살 + 십성 카운트 종합',
    baseScore: 15,
    weights: { ...V2_90, cnt_cheoneul: 5, cnt_gui_total: 5, cnt_insung: 5, cnt_bigeop: 3 },
  },
  { id: 166, name: '#90 + 영진 + 정환 (A4+A5 결합)',
    hypothesis: '비학자 격국 두 sample 동시 강화',
    baseScore: 18,
    weights: { ...V2_90, g_sanggwan: 16, g_jeongjae: 16, d_youthGwansung: 16, cnt_siksang: 2 },
  },
  { id: 167, name: '#58 + 영진/정환 + 사주 강 보너스',
    hypothesis: 'A93 + B2.133',
    baseScore: 18,
    weights: { ...V2_58, g_sanggwan: 14, g_jeongjae: 14, d_youthGwansung: 14, combo_allScholar: 30 },
  },
  { id: 168, name: '모든 학자형 강 + 페널티 0',
    hypothesis: '인플레 가능성 — baseline 비교',
    baseScore: 20,
    weights: { ...V7_BASE, g_jeongin: 28, g_pyeonin: 28, g_jeonggwan: 28, g_siksin: 25, g_pyeongwan: 22, g_yangin: 18, g_bigyeon: 18, s_gwaninCombo: 25, combo_allScholar: 25, combo_jarip: 20 },
  },
  { id: 169, name: '격국 base 차등 + cnt multiplier 종합',
    hypothesis: 'B1.126 + B4.145',
    baseScore: 12,
    weights: { g_jeongin: 30, g_pyeonin: 28, g_jeonggwan: 28, g_pyeongwan: 22, g_siksin: 25, g_bigyeon: 18, g_yangin: 22, g_jeongjae: 12, g_pyeonjae: 10, g_sanggwan: 12, cnt_insung: 4, cnt_gui_total: 4, cnt_cheoneul: 3, s_gwaninCombo: 18 },
  },
  { id: 170, name: '격국 그라데이션 + 콤보 + 신살 카운트 통합',
    hypothesis: 'V2 #88 + B4',
    baseScore: 15,
    weights: { ...V2_88, cnt_cheoneul: 3, cnt_gui_total: 3 },
  },
  { id: 171, name: '9 sample 수동 fit Plot 1',
    hypothesis: '영진·정환 base ↑ + 인성왕 보너스 + 두흥 양인 보너스',
    baseScore: 16,
    weights: { ...V7_BASE, g_jeongin: 25, g_pyeonin: 25, g_jeonggwan: 22, g_siksin: 22, g_pyeongwan: 20, g_yangin: 20, g_bigyeon: 18, g_jeongjae: 15, g_pyeonjae: 12, g_sanggwan: 15, s_gwaninCombo: 22, combo_jarip: 18, combo_yanginScholar: 18, d_youthInsung: 12, d_youthGwansung: 12 },
  },
  { id: 172, name: '9 sample 수동 fit Plot 2',
    hypothesis: 'Plot 1 + cnt multiplier 강',
    baseScore: 14,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_jeonggwan: 22, g_siksin: 20, g_pyeongwan: 18, g_yangin: 18, g_bigyeon: 15, g_jeongjae: 14, g_pyeonjae: 12, g_sanggwan: 14, s_gwaninCombo: 20, cnt_insung: 4, cnt_gui_total: 4, cnt_bigeop: 2, combo_jarip: 15 },
  },
  { id: 173, name: '9 sample 수동 fit Plot 3',
    hypothesis: 'Plot 2 + 청소년 대운 시기별',
    baseScore: 14,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_jeonggwan: 22, g_siksin: 20, g_pyeongwan: 18, g_yangin: 18, g_bigyeon: 15, g_jeongjae: 14, g_pyeonjae: 12, g_sanggwan: 14, s_gwaninCombo: 20, cnt_insung: 4, cnt_gui_total: 4, d_youthInsung: 12, d_youthGwansung: 10, d_examInsung: 8, combo_jarip: 15 },
  },
  { id: 174, name: 'V2 Top 3 평균 + B1.122',
    hypothesis: 'V2 평균 시작점 + 격국 grade',
    baseScore: 16,
    weights: { ...V2_TOP3_AVG, g_jeonggwan: 25, g_siksin: 22, g_pyeongwan: 22 },
  },
  { id: 175, name: 'V2 Top 3 평균 + B1.123',
    hypothesis: 'V2 평균 + 학자형 28',
    baseScore: 16,
    weights: { ...V2_TOP3_AVG, g_jeongin: 28, g_pyeonin: 28, g_jeonggwan: 28 },
  },
  { id: 176, name: 'V2 Top 3 평균 + B5.150 (정재 + 인성 콤보)',
    hypothesis: 'V2 평균 + 정환·와이프 강화',
    baseScore: 16,
    weights: { ...V2_TOP3_AVG, g_jeongjae: 14, s_insung2: 15, s_insung3: 22 },
  },
  { id: 177, name: 'V3 후보 1 — 격국 base + cnt + 콤보',
    hypothesis: '종합 최적화 1',
    baseScore: 14,
    weights: { g_jeongin: 28, g_pyeonin: 28, g_jeonggwan: 28, g_siksin: 25, g_pyeongwan: 22, g_bigyeon: 18, g_yangin: 22, g_jeongjae: 15, g_pyeonjae: 12, g_sanggwan: 15, s_gwaninCombo: 22, combo_allScholar: 20, combo_jarip: 15, cnt_insung: 3, cnt_gui_total: 3 },
  },
  { id: 178, name: 'V3 후보 2 — 격국 + 콤보 강 + 청소년 대운',
    hypothesis: '종합 최적화 2',
    baseScore: 16,
    weights: { ...V7_BASE, g_jeongin: 25, g_pyeonin: 25, g_jeonggwan: 25, g_siksin: 22, g_pyeongwan: 20, g_yangin: 18, g_bigyeon: 15, g_jeongjae: 14, g_pyeonjae: 12, g_sanggwan: 14, s_gwaninCombo: 22, combo_allScholar: 22, combo_jarip: 18, d_youthInsung: 14, d_youthGwansung: 12 },
  },
  { id: 179, name: 'V3 후보 3 — 모든 sample fit 단순',
    hypothesis: '학자형 강 + 비학자 모두 base 학자형의 60-70%',
    baseScore: 15,
    weights: { g_jeongin: 25, g_pyeonin: 25, g_jeonggwan: 25, g_pyeongwan: 22, g_siksin: 22, g_bigyeon: 18, g_yangin: 20, g_jeongjae: 16, g_pyeonjae: 14, g_sanggwan: 16, s_gwaninCombo: 22, combo_allScholar: 20, cnt_insung: 3, cnt_gui_total: 3, d_youthInsung: 12 },
  },
  { id: 180, name: '사주 5요소 통합 (격국·십성·신살·운성·대운)',
    hypothesis: '모든 시그너 종합 — V3 최종 candidate',
    baseScore: 14,
    weights: { g_jeongin: 25, g_pyeonin: 25, g_jeonggwan: 25, g_siksin: 22, g_pyeongwan: 20, g_yangin: 20, g_bigyeon: 16, g_jeongjae: 14, g_pyeonjae: 12, g_sanggwan: 14, s_gwaninCombo: 22, s_insung3: 18, s_insung2: 10, combo_allScholar: 20, combo_jarip: 15, combo_yanginScholar: 15, gw_hakdang: 5, gw_munchang: 5, gw_cheoneul: 5, gw_twoVirtues: 5, u_dayGeonrok: 8, u_dayTonggeun: 8, u_monthStrong: 6, d_youthInsung: 12, d_youthGwansung: 10, d_examInsung: 6 },
  },
];
