// V4 시나리오 60개 — 학파 2개 이상 검증 통과 detector 19개 활용
//
// V3 best (#97: #90 + 정환 강화, totalGap 55) 기준점.
// 새 19 detector (DETECTOR_CANDIDATES_V4.md §2): 격국 콤보 6 + 성격파격 2 + 충형 2 + 흉살 1 + 학자귀인 3 + 균형 1 + 자립 2 + 청소년 1 + cnt 2
//
// 6 Phase × 10 = 60 시나리오:
//   V4-A (181-190): 신규 격국 콤보 단독 weight sweep
//   V4-B (191-200): V3 best + 신규 통합
//   V4-C (201-210): 페널티 정밀화 (pagyeok·yearMonthChung·multipleJahyeong)
//   V4-D (211-220): Layer 2 보강 (amrok·samgwiOmni·youngshik_extended)
//   V4-E (221-230): 청소년 대운 + 일지 인성 정밀화
//   V4-F (231-240): 통합 최강 후보

export interface CalibConfig {
  id: number;
  name: string;
  hypothesis: string;
  baseScore: number;
  weights: Record<string, number>;
}

export const V7_BASE = {
  g_jeongin: 12, g_pyeonin: 12, g_jeonggwan: 12, g_siksin: 12, g_bigyeon: 12,
  s_gwaninCombo: 15, s_insung2: 8, s_insung3: 12,
  gw_hakdang: 4, gw_munchang: 4, gw_mungok: 2, gw_cheoneul: 4, gw_twoVirtues: 5, gw_samgwi: 5, gw_samgi: 5,
  u_dayGeonrok: 5, u_dayTonggeun: 5,
  d_youthInsung: 8, d_youthGwansung: 5,
};

// V3 best #97 weights (V4 starting point)
const V3_BEST = { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_jeonggwan: 22, g_pyeongwan: 15, g_siksin: 18, g_bigyeon: 15, g_yangin: 12, g_jeongjae: 8, g_pyeonjae: 8, g_sanggwan: 8, combo_allScholar: 25, combo_jarip: 20, combo_yanginScholar: 18, combo_youngshik: 12, s_gwaninCombo: 18, cnt_insung: 4, cnt_gui_total: 4, cnt_jaesung: -3, d_youthInsung: 15, d_youthGwansung: 17, d_youthJaesung: -8 };

export const SCENARIOS: CalibConfig[] = [
  // ============ V4-A: 신규 격국 콤보 단독 (181-190) ============

  { id: 181, name: '상관패인 +10 (승희 학자 본질)',
    hypothesis: 'comboSanggwanPaeIn 단독 (자평진전·삼명통회)',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, s_gwaninCombo: 22, combo_sanggwanPaeIn: 10 },
  },
  { id: 182, name: '살인상생 +12 (편관격 학자형)',
    hypothesis: 'comboSalinSangsaeng 단독 (자평진전·삼명통회·사주첩경)',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, s_gwaninCombo: 22, combo_salinSangsaeng: 12 },
  },
  { id: 183, name: '정재용관 +8 (정재격 학자형)',
    hypothesis: 'comboJeongjaeYonggwan 단독 (자평진전·적천수)',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, s_gwaninCombo: 22, combo_jeongjaeYonggwan: 8 },
  },
  { id: 184, name: '양인 식상 +8 (윤수 패턴)',
    hypothesis: 'comboYanginSiksang 단독 (자평진전·연해자평·적천수)',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, s_gwaninCombo: 22, combo_yanginSiksang: 8 },
  },
  { id: 185, name: '4개 신규 격국 콤보 동시 (각 +8)',
    hypothesis: 'sanggwanPaeIn·salinSangsaeng·jeongjaeYonggwan·yanginSiksang 모두',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, s_gwaninCombo: 22, combo_sanggwanPaeIn: 8, combo_salinSangsaeng: 8, combo_jeongjaeYonggwan: 8, combo_yanginSiksang: 8 },
  },
  { id: 186, name: '재관쌍미 +6 + 정인통근다중 +4',
    hypothesis: 'comboJaegwanSsangmi + comboJeonginTonggeunMulti',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, s_gwaninCombo: 22, combo_jaegwanSsangmi: 6, combo_jeonginTonggeunMulti: 4 },
  },
  { id: 187, name: '6개 신규 격국 콤보 모두 (각 +6)',
    hypothesis: 'V4-A 격국 콤보 6개 weight 평균 +6',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, s_gwaninCombo: 22, combo_sanggwanPaeIn: 6, combo_salinSangsaeng: 6, combo_jeongjaeYonggwan: 6, combo_yanginSiksang: 6, combo_jaegwanSsangmi: 6, combo_jeonginTonggeunMulti: 6 },
  },
  { id: 188, name: '6개 신규 콤보 강화 (각 +10)',
    hypothesis: 'V4-A 격국 콤보 weight 강 (+10)',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, s_gwaninCombo: 22, combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 10, combo_jeongjaeYonggwan: 10, combo_yanginSiksang: 10, combo_jaegwanSsangmi: 10, combo_jeonginTonggeunMulti: 10 },
  },
  { id: 189, name: '6개 신규 콤보 차등 (학자형 +12, 비학자 +8)',
    hypothesis: '학자형(sanggwanPaeIn·salinSangsaeng·jeonginTonggeun) +12, 비학자(jeongjaeYonggwan·yanginSiksang·jaegwanSsangmi) +8',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, s_gwaninCombo: 22, combo_sanggwanPaeIn: 12, combo_salinSangsaeng: 12, combo_jeonginTonggeunMulti: 12, combo_jeongjaeYonggwan: 8, combo_yanginSiksang: 8, combo_jaegwanSsangmi: 8 },
  },
  { id: 190, name: 'V3 best + 6개 신규 콤보 (각 +6)',
    hypothesis: 'V3 #97 weight + 6 신규 콤보 추가',
    baseScore: 18,
    weights: { ...V3_BEST, combo_sanggwanPaeIn: 6, combo_salinSangsaeng: 6, combo_jeongjaeYonggwan: 6, combo_yanginSiksang: 6, combo_jaegwanSsangmi: 6, combo_jeonginTonggeunMulti: 6 },
  },

  // ============ V4-B: V3 best + 신규 통합 (191-200) ============

  { id: 191, name: 'V3 #97 + 상관패인 +10 + 살인상생 +10 (승희·두흥)',
    hypothesis: '안 잡히던 sample 강화',
    baseScore: 18,
    weights: { ...V3_BEST, combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 10 },
  },
  { id: 192, name: 'V3 #97 + 정재용관 +10 + 재관쌍미 +8 (정환·와이프)',
    hypothesis: '정환 강화 + 와이프 약 보강',
    baseScore: 18,
    weights: { ...V3_BEST, combo_jeongjaeYonggwan: 10, combo_jaegwanSsangmi: 8 },
  },
  { id: 193, name: 'V3 #97 + 정인통근다중 +6 + 자립비겁다중 +4 (홍규)',
    hypothesis: '홍규 정인격 강화',
    baseScore: 18,
    weights: { ...V3_BEST, combo_jeonginTonggeunMulti: 6, combo_jariplBigeopMulti: 4 },
  },
  { id: 194, name: 'V3 #97 + 4개 신규 학자콤보 (각 +8)',
    hypothesis: '학자형 확장 4개',
    baseScore: 18,
    weights: { ...V3_BEST, combo_sanggwanPaeIn: 8, combo_salinSangsaeng: 8, combo_jeongjaeYonggwan: 8, combo_yanginSiksang: 8 },
  },
  { id: 195, name: 'V3 #97 + 6 신규 콤보 (각 +8) + 영진 안 잡힘',
    hypothesis: 'V4 통합 첫 후보',
    baseScore: 18,
    weights: { ...V3_BEST, combo_sanggwanPaeIn: 8, combo_salinSangsaeng: 8, combo_jeongjaeYonggwan: 8, combo_yanginSiksang: 8, combo_jaegwanSsangmi: 8, combo_jeonginTonggeunMulti: 8 },
  },
  { id: 196, name: 'V3 #97 + 신규 콤보 ×0.7 (조정)',
    hypothesis: 'V3 weight 보존 + 신규 약하게',
    baseScore: 18,
    weights: { ...V3_BEST, combo_sanggwanPaeIn: 7, combo_salinSangsaeng: 8, combo_jeongjaeYonggwan: 6, combo_yanginSiksang: 6, combo_jaegwanSsangmi: 4, combo_jeonginTonggeunMulti: 4 },
  },
  { id: 197, name: 'V3 #97 + 성격 +5 (1티어 5명 보강)',
    hypothesis: 'comboSeonggyeok 추가',
    baseScore: 18,
    weights: { ...V3_BEST, combo_seonggyeok: 5, combo_sanggwanPaeIn: 8, combo_salinSangsaeng: 10, combo_jeongjaeYonggwan: 8 },
  },
  { id: 198, name: 'V3 #97 + 학자형 4 신규콤보 + 성격 +5',
    hypothesis: 'V4 통합 #2',
    baseScore: 18,
    weights: { ...V3_BEST, combo_seonggyeok: 5, combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 12, combo_jeongjaeYonggwan: 8, combo_yanginSiksang: 8 },
  },
  { id: 199, name: 'V3 #97 + 모든 V4 신규 콤보',
    hypothesis: 'V4 detector 모두 활용',
    baseScore: 18,
    weights: { ...V3_BEST, combo_seonggyeok: 5, combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 10, combo_jeongjaeYonggwan: 8, combo_yanginSiksang: 8, combo_jaegwanSsangmi: 6, combo_jeonginTonggeunMulti: 5, combo_jariplBigeopMulti: 3 },
  },
  { id: 200, name: 'V3 #97 - 일부 weight 감소 + 신규 +8 균등',
    hypothesis: 'V3 인플레 줄이고 신규로 다양화',
    baseScore: 15,
    weights: { ...V3_BEST, combo_allScholar: 20, combo_jarip: 15, combo_yanginScholar: 15, d_youthGwansung: 12, combo_sanggwanPaeIn: 8, combo_salinSangsaeng: 8, combo_jeongjaeYonggwan: 8, combo_yanginSiksang: 8, combo_jaegwanSsangmi: 8, combo_jeonginTonggeunMulti: 8 },
  },

  // ============ V4-C: 페널티 정밀화 (201-210) ============

  { id: 201, name: '파격 -8 단독',
    hypothesis: 'penalty_pagyeok 단독 (두흥)',
    baseScore: 18,
    weights: { ...V3_BEST, penalty_pagyeok: -8 },
  },
  { id: 202, name: '년월충 -5 단독',
    hypothesis: 'penalty_yearMonthChung 단독 (두흥)',
    baseScore: 18,
    weights: { ...V3_BEST, penalty_yearMonthChung: -5 },
  },
  { id: 203, name: '자형 다중 -3 단독',
    hypothesis: 'penalty_multipleJahyeong 단독 (승희·정환)',
    baseScore: 18,
    weights: { ...V3_BEST, penalty_multipleJahyeong: -3 },
  },
  { id: 204, name: '페널티 3개 모두 (V3 #97 + )',
    hypothesis: 'pagyeok -8 + yearMonthChung -5 + multipleJahyeong -3',
    baseScore: 18,
    weights: { ...V3_BEST, penalty_pagyeok: -8, penalty_yearMonthChung: -5, penalty_multipleJahyeong: -3 },
  },
  { id: 205, name: '페널티 + 4 신규 학자콤보',
    hypothesis: 'V4 통합 with 페널티',
    baseScore: 18,
    weights: { ...V3_BEST, combo_sanggwanPaeIn: 8, combo_salinSangsaeng: 10, combo_jeongjaeYonggwan: 8, combo_yanginSiksang: 8, penalty_pagyeok: -8, penalty_yearMonthChung: -5, penalty_multipleJahyeong: -3 },
  },
  { id: 206, name: '백호 다중 -3 + 페널티',
    hypothesis: 'penalty_baekhoMulti 추가',
    baseScore: 18,
    weights: { ...V3_BEST, penalty_pagyeok: -8, penalty_yearMonthChung: -5, penalty_multipleJahyeong: -3, penalty_baekhoMulti: -3 },
  },
  { id: 207, name: '페널티 약화 (자형 -1)',
    hypothesis: '자형 페널티 약하게 (정환 1티어와 충돌 회피)',
    baseScore: 18,
    weights: { ...V3_BEST, penalty_pagyeok: -8, penalty_yearMonthChung: -5, penalty_multipleJahyeong: -1 },
  },
  { id: 208, name: '페널티 + 학자형 콤보 강',
    hypothesis: 'V4 통합 학자형 강 + 페널티',
    baseScore: 18,
    weights: { ...V3_BEST, combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 12, combo_jeongjaeYonggwan: 10, combo_yanginSiksang: 10, penalty_pagyeok: -8, penalty_yearMonthChung: -5 },
  },
  { id: 209, name: '파격 -10 강 (두흥 -10)',
    hypothesis: '파격 페널티 강화',
    baseScore: 18,
    weights: { ...V3_BEST, penalty_pagyeok: -10, combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 10 },
  },
  { id: 210, name: '파격+년월충 -15 통합 (두흥 직접 -)',
    hypothesis: '두흥 깎고 다른 sample 보강',
    baseScore: 18,
    weights: { ...V3_BEST, penalty_pagyeok: -10, penalty_yearMonthChung: -5, combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 12, combo_jeongjaeYonggwan: 10, combo_yanginSiksang: 8 },
  },

  // ============ V4-D: Layer 2 보강 (211-220) ============

  { id: 211, name: '암록 +3 단독',
    hypothesis: 'gw_amrok 단독 (Eugene·승희)',
    baseScore: 18,
    weights: { ...V3_BEST, gw_amrok: 3 },
  },
  { id: 212, name: '삼귀 + 학자귀인 다중 +5',
    hypothesis: 'combo_samgwiOmni (윤수)',
    baseScore: 18,
    weights: { ...V3_BEST, combo_samgwiOmni: 5 },
  },
  { id: 213, name: '영식 확장 +5',
    hypothesis: 'gw_youngshik_extended (윤수)',
    baseScore: 18,
    weights: { ...V3_BEST, gw_youngshik_extended: 5 },
  },
  { id: 214, name: 'Layer 2 보강 3개 모두',
    hypothesis: 'amrok + samgwiOmni + youngshik_extended',
    baseScore: 18,
    weights: { ...V3_BEST, gw_amrok: 3, combo_samgwiOmni: 5, gw_youngshik_extended: 5 },
  },
  { id: 215, name: 'Layer 2 + 학자형 신규콤보',
    hypothesis: 'V4 통합 학자귀인 강',
    baseScore: 18,
    weights: { ...V3_BEST, gw_amrok: 3, combo_samgwiOmni: 5, gw_youngshik_extended: 5, combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 12 },
  },
  { id: 216, name: '인성 균형 +4 단독',
    hypothesis: 's_insung_balanced (승희)',
    baseScore: 18,
    weights: { ...V3_BEST, s_insung_balanced: 4 },
  },
  { id: 217, name: '자립 비겁 다중 +3 + 일지 인성 +3',
    hypothesis: 'combo_jariplBigeopMulti + s_dayBranchInsung (홍규·세형·윤수·상수)',
    baseScore: 18,
    weights: { ...V3_BEST, combo_jariplBigeopMulti: 3, s_dayBranchInsung: 3 },
  },
  { id: 218, name: '일지 인성 +5 강 (세형·윤수·상수)',
    hypothesis: 's_dayBranchInsung 강화',
    baseScore: 18,
    weights: { ...V3_BEST, s_dayBranchInsung: 5 },
  },
  { id: 219, name: 'Layer 2 보강 종합 + 일지 인성',
    hypothesis: 'V4 Layer 2 통합',
    baseScore: 18,
    weights: { ...V3_BEST, gw_amrok: 3, combo_samgwiOmni: 5, gw_youngshik_extended: 5, s_insung_balanced: 4, combo_jariplBigeopMulti: 3, s_dayBranchInsung: 5 },
  },
  { id: 220, name: 'V4-D 종합 + V4-A 콤보 4개',
    hypothesis: 'Layer 2 종합 + 학자형 콤보 4',
    baseScore: 18,
    weights: { ...V3_BEST, gw_amrok: 3, combo_samgwiOmni: 5, gw_youngshik_extended: 5, s_insung_balanced: 4, combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 10, combo_jeongjaeYonggwan: 8, combo_yanginSiksang: 8 },
  },

  // ============ V4-E: 청소년 대운 정밀화 (221-230) ============

  { id: 221, name: '청소년 관인동림 +5 단독',
    hypothesis: 'd_youthSalinSangsaeng (세형·두흥)',
    baseScore: 18,
    weights: { ...V3_BEST, d_youthSalinSangsaeng: 5 },
  },
  { id: 222, name: '청소년 관인동림 +8 강',
    hypothesis: 'd_youthSalinSangsaeng 강',
    baseScore: 18,
    weights: { ...V3_BEST, d_youthSalinSangsaeng: 8 },
  },
  { id: 223, name: '관인동림 + V4 신규 콤보',
    hypothesis: '청소년 대운 + 격국 콤보',
    baseScore: 18,
    weights: { ...V3_BEST, d_youthSalinSangsaeng: 5, combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 12 },
  },
  { id: 224, name: '청소년 인성 +18 강 (V3 #97 → +18)',
    hypothesis: 'd_youthInsung 강화 (Eugene·세형·윤수·상수 보강)',
    baseScore: 18,
    weights: { ...V3_BEST, d_youthInsung: 18 },
  },
  { id: 225, name: '청소년 관성 +20 강 (정환·승희·두흥 보강)',
    hypothesis: 'd_youthGwansung 강화',
    baseScore: 18,
    weights: { ...V3_BEST, d_youthGwansung: 20 },
  },
  { id: 226, name: '청소년 인성 + 관성 + 관인동림 통합',
    hypothesis: 'd_youthInsung + d_youthGwansung + d_youthSalinSangsaeng',
    baseScore: 18,
    weights: { ...V3_BEST, d_youthInsung: 18, d_youthGwansung: 18, d_youthSalinSangsaeng: 6 },
  },
  { id: 227, name: '입시 인성 + 입시 관성 강 (d_examInsung + d_exam_gwansung)',
    hypothesis: '입시 직전 대운 강화',
    baseScore: 18,
    weights: { ...V3_BEST, d_examInsung: 12, d_exam_gwansung: 10, d_youthSalinSangsaeng: 5 },
  },
  { id: 228, name: '청소년 + 입시 대운 통합',
    hypothesis: '전 시기 강화',
    baseScore: 18,
    weights: { ...V3_BEST, d_youthInsung: 16, d_youthGwansung: 16, d_youthSalinSangsaeng: 5, d_examInsung: 10, d_exam_gwansung: 8 },
  },
  { id: 229, name: '청소년 학자 + V4 콤보 (3 학자형 격국 콤보)',
    hypothesis: '청소년 강 + 학자콤보 3개',
    baseScore: 18,
    weights: { ...V3_BEST, d_youthInsung: 16, d_youthSalinSangsaeng: 6, combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 12, combo_jeongjaeYonggwan: 8 },
  },
  { id: 230, name: '시기별 + V4 검증 detector 종합',
    hypothesis: 'V4-A + V4-D + V4-E 통합',
    baseScore: 18,
    weights: { ...V3_BEST, d_youthInsung: 16, d_youthSalinSangsaeng: 5, combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 12, combo_jeongjaeYonggwan: 8, combo_yanginSiksang: 8, gw_amrok: 3, gw_youngshik_extended: 5, s_dayBranchInsung: 4 },
  },

  // ============ V4-F: 통합 최강 후보 (231-240) ============

  { id: 231, name: 'V4 통합 #1 — V3 #97 + 모든 V4 detector (균등 +6)',
    hypothesis: '신규 19 detector 모두 균등 +6',
    baseScore: 18,
    weights: { ...V3_BEST,
      combo_sanggwanPaeIn: 6, combo_salinSangsaeng: 6, combo_jeongjaeYonggwan: 6, combo_yanginSiksang: 6, combo_jaegwanSsangmi: 6, combo_jeonginTonggeunMulti: 6,
      combo_seonggyeok: 5, gw_amrok: 3, combo_samgwiOmni: 5, gw_youngshik_extended: 5, s_insung_balanced: 4, combo_jariplBigeopMulti: 3, s_dayBranchInsung: 4, d_youthSalinSangsaeng: 5,
      penalty_pagyeok: -5, penalty_yearMonthChung: -3, penalty_multipleJahyeong: -2 },
  },
  { id: 232, name: 'V4 통합 #2 — 학자형 콤보 강 + 페널티',
    hypothesis: '학자형 격국 콤보 +10, 페널티 −5',
    baseScore: 18,
    weights: { ...V3_BEST,
      combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 12, combo_jeongjaeYonggwan: 10, combo_yanginSiksang: 10,
      combo_seonggyeok: 5, gw_amrok: 3, gw_youngshik_extended: 5,
      penalty_pagyeok: -8, penalty_yearMonthChung: -5 },
  },
  { id: 233, name: 'V4 통합 #3 — sample별 미세 종합',
    hypothesis: '각 sample 강화 콤보 weight 조정',
    baseScore: 18,
    weights: { ...V3_BEST,
      combo_sanggwanPaeIn: 10, // 승희
      combo_salinSangsaeng: 12, // 세형·두흥
      combo_jeongjaeYonggwan: 10, // 정환
      combo_yanginSiksang: 8, // 윤수
      combo_jeonginTonggeunMulti: 5, // Eugene
      combo_jariplBigeopMulti: 3, // Eugene 보강
      s_dayBranchInsung: 4, // 세형·윤수·상수
      gw_amrok: 3, // Eugene·승희
      d_youthSalinSangsaeng: 5, // 세형·두흥
      penalty_pagyeok: -8, penalty_yearMonthChung: -5, penalty_multipleJahyeong: -2 },
  },
  { id: 234, name: 'V4 통합 #4 — V3 best weight 축소 + V4 추가',
    hypothesis: 'V3 inflation 줄이고 V4로 보강',
    baseScore: 15,
    weights: { ...V3_BEST, combo_allScholar: 18, combo_jarip: 14, combo_yanginScholar: 14, combo_youngshik: 8, s_gwaninCombo: 14, cnt_insung: 3, d_youthInsung: 12, d_youthGwansung: 12,
      combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 12, combo_jeongjaeYonggwan: 10, combo_yanginSiksang: 8, combo_seonggyeok: 5, gw_amrok: 3, gw_youngshik_extended: 5, s_dayBranchInsung: 4, d_youthSalinSangsaeng: 5,
      penalty_pagyeok: -8, penalty_yearMonthChung: -5, penalty_multipleJahyeong: -2 },
  },
  { id: 235, name: 'V4 통합 #5 — 격국 콤보 6 + 학자귀인 3 + 페널티',
    hypothesis: '명리 본질 중심',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 20, g_pyeonin: 20, g_jeonggwan: 20, g_pyeongwan: 15, g_siksin: 18, g_yangin: 12, g_bigyeon: 15, g_jeongjae: 10, g_pyeonjae: 8, g_sanggwan: 10,
      s_gwaninCombo: 18, combo_allScholar: 20, combo_jarip: 15, combo_yanginScholar: 15,
      combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 12, combo_jeongjaeYonggwan: 10, combo_yanginSiksang: 8, combo_jaegwanSsangmi: 6, combo_jeonginTonggeunMulti: 5,
      combo_seonggyeok: 5, gw_amrok: 3, combo_samgwiOmni: 4, gw_youngshik_extended: 4,
      s_dayBranchInsung: 4, d_youthInsung: 15, d_youthGwansung: 12, d_youthSalinSangsaeng: 5,
      penalty_pagyeok: -8, penalty_yearMonthChung: -5, penalty_multipleJahyeong: -2 },
  },
  { id: 236, name: 'V4 통합 #6 — 학파 정통 (자평진전 격국 중심)',
    hypothesis: '자평진전 격국론 + 통근 + 청소년 대운',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_jeonggwan: 22, g_pyeongwan: 18, g_siksin: 18,
      combo_seonggyeok: 8, combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 12, combo_jeongjaeYonggwan: 10, combo_yanginSiksang: 8, combo_jeonginTonggeunMulti: 5,
      combo_jariplBigeopMulti: 4, s_dayBranchInsung: 5,
      d_youthInsung: 14, d_youthGwansung: 12, d_youthSalinSangsaeng: 5,
      penalty_pagyeok: -8 },
  },
  { id: 237, name: 'V4 통합 #7 — 학파 정통 + 신살 강화',
    hypothesis: '#236 + 삼명통회 신살 강',
    baseScore: 15,
    weights: { ...V7_BASE, g_jeongin: 22, g_pyeonin: 22, g_jeonggwan: 22, g_pyeongwan: 18, g_siksin: 18,
      gw_hakdang: 6, gw_munchang: 6, gw_cheoneul: 6, gw_twoVirtues: 6, gw_samgwi: 6, gw_amrok: 4,
      combo_youngshik: 8, combo_samgwiOmni: 6, gw_youngshik_extended: 6,
      combo_seonggyeok: 6, combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 12, combo_jeongjaeYonggwan: 10, combo_yanginSiksang: 8,
      d_youthInsung: 12, d_youthSalinSangsaeng: 5,
      penalty_pagyeok: -8 },
  },
  { id: 238, name: 'V4 통합 #8 — 사주 5요소 균형',
    hypothesis: '격국·십성·신살·운성·대운 각 균형',
    baseScore: 14,
    weights: { g_jeongin: 22, g_pyeonin: 22, g_jeonggwan: 22, g_pyeongwan: 18, g_siksin: 20, g_bigyeon: 15, g_yangin: 15, g_jeongjae: 12, g_sanggwan: 12, g_pyeonjae: 10,
      s_gwaninCombo: 18, s_insung3: 15, s_insung2: 10, s_gui_2plus: 12,
      gw_hakdang: 5, gw_munchang: 5, gw_cheoneul: 5, gw_twoVirtues: 5, gw_amrok: 4,
      u_dayGeonrok: 8, u_dayTonggeun: 8, u_monthStrong: 6,
      d_youthInsung: 12, d_youthGwansung: 10, d_youthSalinSangsaeng: 5,
      combo_seonggyeok: 5, combo_sanggwanPaeIn: 10, combo_salinSangsaeng: 12, combo_jeongjaeYonggwan: 10, combo_yanginSiksang: 8, combo_jaegwanSsangmi: 6, combo_jeonginTonggeunMulti: 5,
      penalty_pagyeok: -8, penalty_yearMonthChung: -5, penalty_multipleJahyeong: -2 },
  },
  { id: 239, name: 'V4 통합 #9 — 보수적 (V3 best 유지 + 신규 약하게)',
    hypothesis: 'V3 #97 + 신규 모두 +4 균등',
    baseScore: 18,
    weights: { ...V3_BEST,
      combo_sanggwanPaeIn: 4, combo_salinSangsaeng: 4, combo_jeongjaeYonggwan: 4, combo_yanginSiksang: 4, combo_jaegwanSsangmi: 4, combo_jeonginTonggeunMulti: 4,
      combo_seonggyeok: 3, gw_amrok: 2, combo_samgwiOmni: 3, gw_youngshik_extended: 3, s_insung_balanced: 2, combo_jariplBigeopMulti: 2, s_dayBranchInsung: 2, d_youthSalinSangsaeng: 3,
      penalty_pagyeok: -3, penalty_yearMonthChung: -2 },
  },
  { id: 240, name: 'V4 통합 #10 — 공격적 (학자형 콤보 +15 강)',
    hypothesis: '학자형 격국 콤보 매우 강',
    baseScore: 15,
    weights: { ...V3_BEST,
      combo_sanggwanPaeIn: 15, combo_salinSangsaeng: 15, combo_jeongjaeYonggwan: 12, combo_yanginSiksang: 12,
      combo_seonggyeok: 8, gw_amrok: 4, gw_youngshik_extended: 6, s_dayBranchInsung: 5, d_youthSalinSangsaeng: 6,
      penalty_pagyeok: -10, penalty_yearMonthChung: -5 },
  },
];
