// V7 시나리오 30개 — 홍규·세형 1-2 매핑 보강 (정환 weight 0.5로 감쇠)
//
// V6 best Loop 266 (totalGap 47, sample weight: 정환 1).
// V7 변경: 정환 weight 0.5 (외부의지 인정) + 홍규·세형 강화.
//   목표: 홍규 raw 101 → 108+ (2-2 도달, +7), 세형 raw 105 → 108+ (+3).
//
// 30 시나리오:
//   V7-A (271-280): 홍규 강화 (정인격·자립학자·정인통근다중·인성 multi·비겁)
//   V7-B (281-289): 세형 강화 (살인상생·청소년 관인동림·학자귀인 multi·일주 제왕)
//   V7-C (290-300): 통합 + 균형

export interface CalibConfig {
  id: number;
  name: string;
  hypothesis: string;
  baseScore: number;
  weights: Record<string, number>;
}

export const V7_BASE = {
  g_jeongin: 12, g_pyeonin: 12, g_jeonggwan: 12, g_siksin: 12, g_bigyeon: 12,
  s_gwaninCombo: 15, s_insung2: 8, s_insung3: 12,
  gw_hakdang: 4, gw_munchang: 4, gw_mungok: 2, gw_cheoneul: 4, gw_twoVirtues: 5, gw_samgwi: 5, gw_samgi: 5,
  u_dayGeonrok: 5, u_dayTonggeun: 5,
  d_youthInsung: 8, d_youthGwansung: 5,
};

// V6 best (Loop 266) weight = V4 best + V5 변경
const V6_BEST = {
  ...V7_BASE,
  // V3 best override
  g_jeongin: 22, g_pyeonin: 22, g_jeonggwan: 22, g_pyeongwan: 15, g_siksin: 18, g_bigyeon: 15, g_yangin: 12, g_jeongjae: 8, g_pyeonjae: 8, g_sanggwan: 8,
  combo_allScholar: 25, combo_jarip: 20, combo_yanginScholar: 18, combo_youngshik: 12,
  s_gwaninCombo: 18,
  cnt_insung: 4, cnt_gui_total: 4, cnt_jaesung: -3,
  d_youthInsung: 15, d_youthGwansung: 17, d_youthJaesung: -8,
  // V4 6 콤보
  combo_sanggwanPaeIn: 8, combo_salinSangsaeng: 8, combo_jeongjaeYonggwan: 8,
  combo_yanginSiksang: 8, combo_jaegwanSsangmi: 4, combo_jeonginTonggeunMulti: 8,
  // V5
  s_jaeGwanIn_samgwi: 5, cnt_gwangwiHakgwan: 8, combo_cheonEulHakdang: 5,
};

export const SCENARIOS: CalibConfig[] = [
  // ============ V7-A: 홍규 강화 (정인격, 자립학자, 인성·비겁, 271-280) ============

  { id: 271, name: '정인 통근 다중 +15 (V6 8→15)',
    hypothesis: 'combo_jeonginTonggeunMulti 강화 — 홍규 +7',
    baseScore: 18,
    weights: { ...V6_BEST, combo_jeonginTonggeunMulti: 15 },
  },
  { id: 272, name: '자립학자 +28 (V6 20→28)',
    hypothesis: 'combo_jarip 강화 — 홍규 +8',
    baseScore: 18,
    weights: { ...V6_BEST, combo_jarip: 28 },
  },
  { id: 273, name: '자립 비겁 다중 +6 신규 추가',
    hypothesis: 'combo_jariplBigeopMulti — 홍규 정인격+일지건록+비겁≥3 발동',
    baseScore: 18,
    weights: { ...V6_BEST, combo_jariplBigeopMulti: 6 },
  },
  { id: 274, name: '일주 건록 +12 (V6 5→12)',
    hypothesis: 'u_dayGeonrok 강화 — 홍규·정환 모두 영향 ✗ (정환 일지 미)',
    baseScore: 18,
    weights: { ...V6_BEST, u_dayGeonrok: 12 },
  },
  { id: 275, name: '인성 multiplier ×6 (V6 ×4)',
    hypothesis: 'cnt_insung ×6 — 홍규 +4, 윤수 +2',
    baseScore: 18,
    weights: { ...V6_BEST, cnt_insung: 6 },
  },
  { id: 276, name: '비겁 multiplier ×3 신규',
    hypothesis: 'cnt_bigeop ×3 — 홍규 비겁 4 → +12',
    baseScore: 18,
    weights: { ...V6_BEST, cnt_bigeop: 3 },
  },
  { id: 277, name: '자립학자 강 통합 (271+272+273)',
    hypothesis: '정인 통근 + 자립 + 비겁 다중 통합',
    baseScore: 18,
    weights: { ...V6_BEST, combo_jeonginTonggeunMulti: 15, combo_jarip: 25, combo_jariplBigeopMulti: 6 },
  },
  { id: 278, name: '정인격 base 22 → 28',
    hypothesis: 'g_jeongin 강화 — 홍규 +6',
    baseScore: 18,
    weights: { ...V6_BEST, g_jeongin: 28 },
  },
  { id: 279, name: '홍규 통합 #1 (정인 통근 + 자립 + 비겁 multi)',
    hypothesis: '271 + 272 + 276',
    baseScore: 18,
    weights: { ...V6_BEST, combo_jeonginTonggeunMulti: 15, combo_jarip: 28, cnt_bigeop: 3 },
  },
  { id: 280, name: '홍규 통합 #2 (정인격 + 자립 + 인성 multi 강)',
    hypothesis: '278 + 277 + 275',
    baseScore: 18,
    weights: { ...V6_BEST, g_jeongin: 28, combo_jeonginTonggeunMulti: 15, combo_jarip: 28, combo_jariplBigeopMulti: 6, cnt_insung: 6 },
  },

  // ============ V7-B: 세형 강화 (살인상생, 청소년 관인동림, 학자귀인 multi, 281-289) ============

  { id: 281, name: '살인상생 +18 (V6 8→18)',
    hypothesis: 'combo_salinSangsaeng 강화 — 세형·두흥 +10',
    baseScore: 18,
    weights: { ...V6_BEST, combo_salinSangsaeng: 18 },
  },
  { id: 282, name: '청소년 관인동림 +8',
    hypothesis: 'd_youthSalinSangsaeng 신규 weight — 세형·두흥 발동',
    baseScore: 18,
    weights: { ...V6_BEST, d_youthSalinSangsaeng: 8 },
  },
  { id: 283, name: '학자귀인 multi (학당·문창 boolean→count)',
    hypothesis: 'cnt_hakdang ×4, cnt_munchang ×4 추가 — 세형 학당 2 → +4',
    baseScore: 18,
    weights: { ...V6_BEST, cnt_hakdang: 4, cnt_munchang: 4 },
  },
  { id: 284, name: '편관격 base 15 → 22 (세형 강화)',
    hypothesis: 'g_pyeongwan 강화 — 세형·두흥 +7',
    baseScore: 18,
    weights: { ...V6_BEST, g_pyeongwan: 22 },
  },
  { id: 285, name: '천덕월덕 +10 (V6 5→10)',
    hypothesis: 'gw_twoVirtues 강화 — 세형·윤수·와이프 영향',
    baseScore: 18,
    weights: { ...V6_BEST, gw_twoVirtues: 10 },
  },
  { id: 286, name: '일주 제왕 +5 신규',
    hypothesis: 'u_dayJewang 신규 weight — 세형 +5',
    baseScore: 18,
    weights: { ...V6_BEST, u_dayJewang: 5 },
  },
  { id: 287, name: '살인상생 + 학자귀인 multi (281+283)',
    hypothesis: '세형 통합 #1',
    baseScore: 18,
    weights: { ...V6_BEST, combo_salinSangsaeng: 18, cnt_hakdang: 4, cnt_munchang: 4 },
  },
  { id: 288, name: '살인상생 + 관인동림 + 일주 제왕 (281+282+286)',
    hypothesis: '세형 통합 #2',
    baseScore: 18,
    weights: { ...V6_BEST, combo_salinSangsaeng: 18, d_youthSalinSangsaeng: 8, u_dayJewang: 5 },
  },
  { id: 289, name: '세형 종합 통합 (281+282+283+285+286)',
    hypothesis: '편관격 + 신살 강화 모두',
    baseScore: 18,
    weights: { ...V6_BEST, combo_salinSangsaeng: 18, d_youthSalinSangsaeng: 8, cnt_hakdang: 4, cnt_munchang: 4, gw_twoVirtues: 10, u_dayJewang: 5 },
  },

  // ============ V7-C: 통합 + 균형 (290-300) ============

  { id: 290, name: 'V7-A + V7-B 균등 통합',
    hypothesis: '홍규 + 세형 강화 동시',
    baseScore: 18,
    weights: { ...V6_BEST,
      // 홍규
      combo_jeonginTonggeunMulti: 15, combo_jarip: 28, combo_jariplBigeopMulti: 6, cnt_bigeop: 3,
      // 세형
      combo_salinSangsaeng: 18, d_youthSalinSangsaeng: 8, u_dayJewang: 5 },
  },
  { id: 291, name: 'V7-A 강 + V7-B 약',
    hypothesis: '홍규 우선',
    baseScore: 18,
    weights: { ...V6_BEST,
      g_jeongin: 28, combo_jeonginTonggeunMulti: 18, combo_jarip: 30, combo_jariplBigeopMulti: 8, cnt_bigeop: 4,
      combo_salinSangsaeng: 12, d_youthSalinSangsaeng: 5 },
  },
  { id: 292, name: 'V7-A 약 + V7-B 강',
    hypothesis: '세형 우선',
    baseScore: 18,
    weights: { ...V6_BEST,
      combo_jeonginTonggeunMulti: 12, combo_jarip: 25, cnt_bigeop: 2,
      combo_salinSangsaeng: 22, d_youthSalinSangsaeng: 10, cnt_hakdang: 4, cnt_munchang: 4, u_dayJewang: 5 },
  },
  { id: 293, name: '통합 + cnt_insung ×6 강',
    hypothesis: '290 + 인성 multi 강 — 윤수·상수 영향',
    baseScore: 18,
    weights: { ...V6_BEST,
      combo_jeonginTonggeunMulti: 15, combo_jarip: 28, combo_jariplBigeopMulti: 6, cnt_bigeop: 3,
      combo_salinSangsaeng: 18, d_youthSalinSangsaeng: 8, u_dayJewang: 5,
      cnt_insung: 6 },
  },
  { id: 294, name: '통합 + 청소년 대운 강',
    hypothesis: '290 + d_youthInsung 강 (15→20)',
    baseScore: 18,
    weights: { ...V6_BEST,
      combo_jeonginTonggeunMulti: 15, combo_jarip: 28, combo_jariplBigeopMulti: 6, cnt_bigeop: 3,
      combo_salinSangsaeng: 18, d_youthSalinSangsaeng: 8, u_dayJewang: 5,
      d_youthInsung: 20 },
  },
  { id: 295, name: '통합 + 콤보 강',
    hypothesis: '290 + combo_allScholar 25→32',
    baseScore: 18,
    weights: { ...V6_BEST,
      combo_jeonginTonggeunMulti: 15, combo_jarip: 28, combo_jariplBigeopMulti: 6, cnt_bigeop: 3,
      combo_salinSangsaeng: 18, d_youthSalinSangsaeng: 8, u_dayJewang: 5,
      combo_allScholar: 32 },
  },
  { id: 296, name: '통합 보수적 (overshoot 회피)',
    hypothesis: 'A·B 약하게',
    baseScore: 18,
    weights: { ...V6_BEST,
      combo_jeonginTonggeunMulti: 12, combo_jarip: 24, combo_jariplBigeopMulti: 4, cnt_bigeop: 2,
      combo_salinSangsaeng: 14, d_youthSalinSangsaeng: 5 },
  },
  { id: 297, name: '통합 공격적 (최강)',
    hypothesis: 'A·B 매우 강 — overshoot 우려',
    baseScore: 18,
    weights: { ...V6_BEST,
      g_jeongin: 30, combo_jeonginTonggeunMulti: 20, combo_jarip: 35, combo_jariplBigeopMulti: 10, cnt_bigeop: 5,
      combo_salinSangsaeng: 25, d_youthSalinSangsaeng: 12, cnt_hakdang: 6, cnt_munchang: 6, gw_twoVirtues: 12, u_dayJewang: 8 },
  },
  { id: 298, name: '통합 균형 #1 (홍규·세형 둘 다 +7 raw 보강)',
    hypothesis: '정밀 fit',
    baseScore: 18,
    weights: { ...V6_BEST,
      combo_jarip: 28, combo_jariplBigeopMulti: 6,
      combo_salinSangsaeng: 16, u_dayJewang: 6, cnt_hakdang: 4 },
  },
  { id: 299, name: 'V7 최강 통합 (모든 신규 weight)',
    hypothesis: '명리 신호 종합',
    baseScore: 18,
    weights: { ...V6_BEST,
      g_jeongin: 26,
      combo_jeonginTonggeunMulti: 14, combo_jarip: 28, combo_jariplBigeopMulti: 6, cnt_bigeop: 3, cnt_insung: 5,
      combo_salinSangsaeng: 18, d_youthSalinSangsaeng: 8, cnt_hakdang: 4, cnt_munchang: 4, gw_twoVirtues: 8, u_dayJewang: 5,
      g_pyeongwan: 18 },
  },
  { id: 300, name: 'V7 균형 종합 + cap',
    hypothesis: 'V7 모든 신규 + cap',
    baseScore: 16,
    weights: { ...V6_BEST,
      g_jeongin: 25,
      combo_jeonginTonggeunMulti: 12, combo_jarip: 25, combo_jariplBigeopMulti: 4, cnt_bigeop: 2,
      combo_salinSangsaeng: 15, d_youthSalinSangsaeng: 6, cnt_hakdang: 3, cnt_munchang: 3, u_dayJewang: 4 },
  },
];
